// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQCgMQWBtINsUWHOmkvzcgjWOvr9wgFxQ',
    appId: '1:715658775952:web:bfba7f2124fa0506567715',
    messagingSenderId: '715658775952',
    projectId: 'bloodlink-1166a',
    authDomain: 'bloodlink-1166a.firebaseapp.com',
    storageBucket: 'bloodlink-1166a.firebasestorage.app',
    measurementId: 'G-QBMBR1T6V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3DDNvsilgfv9FhTipJxPD4DkII80pUKI',
    appId: '1:715658775952:android:1bd485843842e601567715',
    messagingSenderId: '715658775952',
    projectId: 'bloodlink-1166a',
    storageBucket: 'bloodlink-1166a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRIKBcTej0vN230um_x3oAPQ-haZHy24k',
    appId: '1:715658775952:ios:1f3bee6637b3a256567715',
    messagingSenderId: '715658775952',
    projectId: 'bloodlink-1166a',
    storageBucket: 'bloodlink-1166a.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRIKBcTej0vN230um_x3oAPQ-haZHy24k',
    appId: '1:715658775952:ios:1f3bee6637b3a256567715',
    messagingSenderId: '715658775952',
    projectId: 'bloodlink-1166a',
    storageBucket: 'bloodlink-1166a.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQCgMQWBtINsUWHOmkvzcgjWOvr9wgFxQ',
    appId: '1:715658775952:web:148ff7509b2c74e2567715',
    messagingSenderId: '715658775952',
    projectId: 'bloodlink-1166a',
    authDomain: 'bloodlink-1166a.firebaseapp.com',
    storageBucket: 'bloodlink-1166a.firebasestorage.app',
    measurementId: 'G-8G3LSK97X8',
  );
}
